/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) MPC_N20_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};

/* MPC_N20_expl_vde_forw:(i0[2],i1[2x2],i2[2],i3,i4[])->(o0[2],o1[2x2],o2[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a2=-1.5707963267948966e+00;
  a2=(a1<=a2);
  a2=(!a2);
  a3=5.2359877559829882e-01;
  a3=(a3<=a1);
  a3=(!a3);
  a4=3.;
  a1=(a4*a1);
  a5=cos(a1);
  a5=(a4*a5);
  a6=(a3?a5:0);
  a6=(a2?a6:0);
  a6=atan(a6);
  a7=cos(a6);
  a8=(a0*a7);
  a9=9.8100000000000005e+00;
  a10=sin(a6);
  a10=(a9*a10);
  a11=cos(a6);
  a12=(a10*a11);
  a8=(a8-a12);
  if (res[0]!=0) res[0][1]=a8;
  a8=arg[1]? arg[1][1] : 0;
  if (res[1]!=0) res[1][0]=a8;
  a8=sin(a6);
  a12=sin(a1);
  a13=arg[1]? arg[1][0] : 0;
  a13=(a4*a13);
  a13=(a12*a13);
  a13=(a4*a13);
  a14=1.;
  a15=casadi_sq(a5);
  a15=(a3?a15:0);
  a15=(a2?a15:0);
  a15=(a3?a15:0);
  a15=(a2?a15:0);
  a15=(a14+a15);
  a13=(a13/a15);
  a16=(a8*a13);
  a16=(a0*a16);
  a17=sin(a6);
  a18=(a17*a13);
  a18=(a10*a18);
  a19=cos(a6);
  a13=(a19*a13);
  a13=(a9*a13);
  a13=(a11*a13);
  a18=(a18-a13);
  a16=(a16-a18);
  a16=(a3?a16:0);
  a16=(a2?a16:0);
  if (res[1]!=0) res[1][1]=a16;
  a16=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][2]=a16;
  a16=arg[1]? arg[1][2] : 0;
  a16=(a4*a16);
  a12=(a12*a16);
  a12=(a4*a12);
  a12=(a12/a15);
  a8=(a8*a12);
  a8=(a0*a8);
  a17=(a17*a12);
  a17=(a10*a17);
  a19=(a19*a12);
  a19=(a9*a19);
  a19=(a11*a19);
  a17=(a17-a19);
  a8=(a8-a17);
  a8=(a3?a8:0);
  a8=(a2?a8:0);
  if (res[1]!=0) res[1][3]=a8;
  a8=arg[2]? arg[2][1] : 0;
  if (res[2]!=0) res[2][0]=a8;
  a8=sin(a6);
  a1=sin(a1);
  a17=arg[2]? arg[2][0] : 0;
  a17=(a4*a17);
  a1=(a1*a17);
  a4=(a4*a1);
  a5=casadi_sq(a5);
  a5=(a3?a5:0);
  a5=(a2?a5:0);
  a5=(a3?a5:0);
  a5=(a2?a5:0);
  a14=(a14+a5);
  a4=(a4/a14);
  a8=(a8*a4);
  a0=(a0*a8);
  a8=sin(a6);
  a8=(a8*a4);
  a10=(a10*a8);
  a6=cos(a6);
  a6=(a6*a4);
  a9=(a9*a6);
  a11=(a11*a9);
  a10=(a10-a11);
  a0=(a0-a10);
  a3=(a3?a0:0);
  a2=(a2?a3:0);
  a7=(a7+a2);
  if (res[2]!=0) res[2][1]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int MPC_N20_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int MPC_N20_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int MPC_N20_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void MPC_N20_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int MPC_N20_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void MPC_N20_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void MPC_N20_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void MPC_N20_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int MPC_N20_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int MPC_N20_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real MPC_N20_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* MPC_N20_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* MPC_N20_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_N20_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_N20_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int MPC_N20_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int MPC_N20_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
