/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) NMPC_20250909_121625_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};

/* NMPC_20250909_121625_expl_vde_adj:(i0[2],i1[2],i2,i3[0])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10;
  a00=5.2359877559829882e-01;
  a01=arg[0]? arg[0][0] : 0;
  a00=(a00<=a01);
  a00=(!a00);
  a02=-1.5707963267948966e+00;
  a02=(a01<=a02);
  a02=(!a02);
  a03=3.;
  a01=(a03*a01);
  a04=sin(a01);
  a01=cos(a01);
  a01=(a03*a01);
  a05=(a00?a01:0);
  a05=(a02?a05:0);
  a05=atan(a05);
  a06=sin(a05);
  a07=9.8100000000000005e+00;
  a08=(a07*a06);
  a09=arg[1]? arg[1][1] : 0;
  a08=(a08*a09);
  a08=(a06*a08);
  a05=cos(a05);
  a10=(a05*a09);
  a07=(a07*a10);
  a05=(a05*a07);
  a08=(a08-a05);
  a05=arg[2]? arg[2][0] : 0;
  a05=(a05*a09);
  a06=(a06*a05);
  a08=(a08-a06);
  a06=1.;
  a01=casadi_sq(a01);
  a01=(a00?a01:0);
  a01=(a02?a01:0);
  a01=(a00?a01:0);
  a01=(a02?a01:0);
  a06=(a06+a01);
  a08=(a08/a06);
  a08=(a03*a08);
  a04=(a04*a08);
  a03=(a03*a04);
  a03=(-a03);
  a02=(a02?a03:0);
  a00=(a00?a02:0);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int NMPC_20250909_121625_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int NMPC_20250909_121625_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int NMPC_20250909_121625_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void NMPC_20250909_121625_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int NMPC_20250909_121625_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void NMPC_20250909_121625_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void NMPC_20250909_121625_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void NMPC_20250909_121625_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int NMPC_20250909_121625_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int NMPC_20250909_121625_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real NMPC_20250909_121625_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* NMPC_20250909_121625_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* NMPC_20250909_121625_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* NMPC_20250909_121625_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* NMPC_20250909_121625_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int NMPC_20250909_121625_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int NMPC_20250909_121625_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
